### ISSUE TITLE
1.0.2 deployed cleanly, default login not working

### ISSUE THREAD

**Issue by gedroberts** [vosaocms/vosao#608]
I have tried deploying the new 1.0.2 version into a new AppEngine app and 
although Vosao deploys cleanly, I can't log in with the default username 
and password (admin@test.com/admin). I am running Java version 
1.7.0_79-b15. There are no abnormal log entries in the console.
 
Has anyone seen this behaviour?

**Comment by vosaocms** [comment]
Issue closed with 1.0.3 downlable version
