### ISSUE TITLE
The maven build is broken

### ISSUE THREAD

**Issue by ZiglioNZ** [vosaocms/vosao#609]
Since yesterday I can't rebuild vosao anymore.
A few dependencies have changed location, for example:

from
http://repo1.maven.org/maven2/velocity-tools/velocity-tools/

to
http://repo1.maven.org/maven2/org/apache/velocity/velocity-tools/2.0/

So that's an easy changem in api/pom.xml:

```
               <dependency>
		    <groupId>org.apache.velocity</groupId>
		    <artifactId>velocity-tools</artifactId>
		    <version>2.0</version>
		</dependency>

```

Others are more complicated, for example bliki-core used to reference a pom on googlecode:
```
        <repository>
            <id>info-bliki-repository</id>
            <url>http://gwtwiki.googlecode.com/svn/maven-repository/</url>

```

I don't think that's available anymore. Plus other problems, for example maven can't find a lot of artifacts from google, such as gdata. It's a mess!

**Comment by ZiglioNZ** [comment]
Here are some changes that have allowed me to build, still testing
https://github.com/Sirtrack/vosao/commit/a970ea959614c2f66a5fc54eae8a4271884af360

**Comment by vosaocms** [comment]
Issue based on old version
Please use latest
