### ISSUE TITLE
Vosao CMS deployed on GAE platform

### ISSUE THREAD

**Issue by ilmarietto** [vosaocms/vosao#610]
I deployed my web site based on Vosao CMS on Google App Engine platform. It worked well for 4 years but suddenly some months ago something occurred, I do not what, but now my application appears as a void installation of the CMS Vosao. 
Also the user account are missing: my admin user for  example does not exist anymore, I can log in to the CMS just by using the default admin user provides by the base installation.

In fact the google datastore appears as the initial version when the CMS was installed. Any subsequent updates are missing.

The last version of data stored into the database was lost!
I didn't made any changes since 1 year at least!

I contacted google support to understand what happened with the datastore, where is my data, but google said that thay cannot restore the data.

Google support replies to me that the data is still there but the current setup of Vosao isn’t using it. There may be an error being thrown during the configuration workflow which I may need to change to use the old data. They also mention that the issue is related to vosao not being robust to handle a reboot/upgrade/etc. and not related to GCP.

Google support said that data is still there but they do not provide me the access to this data or the access parameters. 

My question is: which is the setup file containing the connection parameter of the google datastore?
How the connection to google datastore works?

I need to check whichn Vosao is correctly configured and that I'm linking to the correct datastore. 

Any help would be apreciated.

With best regards.
Mario

**Comment by vosaocms** [comment]
Hi Mario,

You should have posted a comment in the Vosao Google Group. We would have answered to you more quikly. I was victim myself of this bug 
https://groups.google.com/forum/#!topic/vosao-cms-development/wcw-5S-KebY
before correcting a security lack bigger than the universe...
This issue was reported in #607 

Cheers
